<div class="hero-unit">
	<h1>Welcome!</h1>
	<p>This admin panel has been generated by the FuelPHP Framework.</p>
	<p><a class="btn primary large" href="http://docs.fuelphp.com">Read the Docs</a></p>
</div>
