<?php
$config = array(
	'\Model_OauthProvider' => array(
		array('id' => 1, 'name' => 'Facebook'),
		array('id' => 2, 'name' => 'Twitter'),
		array('id' => 3, 'name' => 'Google'),
	),
	'\Model_Profile' => array(
		array(
			'id' => 1,
			'name' => 'self_introduction',
			'caption' => '自己紹介',
			'display_type' => 1,
			'is_required' => 0,
			'is_unique' => 0,
			'is_edit_public_flag' => 0,
			'default_public_flag' => 1,
			'is_disp_regist' => 1,
			'is_disp_config' => 1,
			'is_disp_search' => 0,
			'form_type' => 'textarea',
			'value_type' => 'string',
			'value_regexp' => '',
			'value_min' => '',
			'value_max' => '',
			'sort_order' => 10,
		),
		array(
			'id' => 2,
			'name' => 'prefecture',
			'caption' => '都道府県',
			'display_type' => 1,
			'is_required' => 0,
			'is_unique' => 0,
			'is_edit_public_flag' => 1,
			'default_public_flag' => 2,
			'is_disp_regist' => 1,
			'is_disp_config' => 1,
			'is_disp_search' => 1,
			'form_type' => 'select',
			'value_type' => 'string',
			'value_regexp' => '',
			'value_min' => '',
			'value_max' => '',
			'sort_order' => 20,
		),
	),
	'\Model_ProfileOption' => array(
		array('id' => 1, 'label' => '北海道', 'profile_id' => '2', 'sort_order' => 10),
		array('id' => 2, 'label' => '青森県', 'profile_id' => '2', 'sort_order' => 20),
		array('id' => 3, 'label' => '岩手県', 'profile_id' => '2', 'sort_order' => 30),
		array('id' => 4, 'label' => '宮城県', 'profile_id' => '2', 'sort_order' => 40),
		array('id' => 5, 'label' => '秋田県', 'profile_id' => '2', 'sort_order' => 50),
		array('id' => 6, 'label' => '山形県', 'profile_id' => '2', 'sort_order' => 60),
		array('id' => 7, 'label' => '福島県', 'profile_id' => '2', 'sort_order' => 70),
		array('id' => 8, 'label' => '茨城県', 'profile_id' => '2', 'sort_order' => 80),
		array('id' => 9, 'label' => '栃木県', 'profile_id' => '2', 'sort_order' => 90),
		array('id' => 10, 'label' => '群馬県', 'profile_id' => '2', 'sort_order' => 100),
		array('id' => 11, 'label' => '埼玉県', 'profile_id' => '2', 'sort_order' => 110),
		array('id' => 12, 'label' => '千葉県', 'profile_id' => '2', 'sort_order' => 120),
		array('id' => 13, 'label' => '東京都', 'profile_id' => '2', 'sort_order' => 130),
		array('id' => 14, 'label' => '神奈川県', 'profile_id' => '2', 'sort_order' => 140),
		array('id' => 15, 'label' => '新潟県', 'profile_id' => '2', 'sort_order' => 150),
		array('id' => 16, 'label' => '富山県', 'profile_id' => '2', 'sort_order' => 160),
		array('id' => 17, 'label' => '石川県', 'profile_id' => '2', 'sort_order' => 170),
		array('id' => 18, 'label' => '福井県', 'profile_id' => '2', 'sort_order' => 180),
		array('id' => 19, 'label' => '山梨県', 'profile_id' => '2', 'sort_order' => 190),
		array('id' => 20, 'label' => '長野県', 'profile_id' => '2', 'sort_order' => 200),
		array('id' => 21, 'label' => '岐阜県', 'profile_id' => '2', 'sort_order' => 210),
		array('id' => 22, 'label' => '静岡県', 'profile_id' => '2', 'sort_order' => 220),
		array('id' => 23, 'label' => '愛知県', 'profile_id' => '2', 'sort_order' => 230),
		array('id' => 24, 'label' => '三重県', 'profile_id' => '2', 'sort_order' => 240),
		array('id' => 25, 'label' => '滋賀県', 'profile_id' => '2', 'sort_order' => 250),
		array('id' => 26, 'label' => '京都府', 'profile_id' => '2', 'sort_order' => 260),
		array('id' => 27, 'label' => '大阪府', 'profile_id' => '2', 'sort_order' => 270),
		array('id' => 28, 'label' => '兵庫県', 'profile_id' => '2', 'sort_order' => 280),
		array('id' => 29, 'label' => '奈良県', 'profile_id' => '2', 'sort_order' => 290),
		array('id' => 30, 'label' => '和歌山県', 'profile_id' => '2', 'sort_order' => 300),
		array('id' => 31, 'label' => '鳥取県', 'profile_id' => '2', 'sort_order' => 310),
		array('id' => 32, 'label' => '島根県', 'profile_id' => '2', 'sort_order' => 320),
		array('id' => 33, 'label' => '岡山県', 'profile_id' => '2', 'sort_order' => 330),
		array('id' => 34, 'label' => '広島県', 'profile_id' => '2', 'sort_order' => 340),
		array('id' => 35, 'label' => '山口県', 'profile_id' => '2', 'sort_order' => 350),
		array('id' => 36, 'label' => '徳島県', 'profile_id' => '2', 'sort_order' => 360),
		array('id' => 37, 'label' => '香川県', 'profile_id' => '2', 'sort_order' => 370),
		array('id' => 38, 'label' => '愛媛県', 'profile_id' => '2', 'sort_order' => 380),
		array('id' => 39, 'label' => '高知県', 'profile_id' => '2', 'sort_order' => 390),
		array('id' => 40, 'label' => '福岡県', 'profile_id' => '2', 'sort_order' => 400),
		array('id' => 41, 'label' => '佐賀県', 'profile_id' => '2', 'sort_order' => 410),
		array('id' => 42, 'label' => '長崎県', 'profile_id' => '2', 'sort_order' => 420),
		array('id' => 43, 'label' => '熊本県', 'profile_id' => '2', 'sort_order' => 430),
		array('id' => 44, 'label' => '大分県', 'profile_id' => '2', 'sort_order' => 440),
		array('id' => 45, 'label' => '宮崎県', 'profile_id' => '2', 'sort_order' => 450),
		array('id' => 46, 'label' => '鹿児島県', 'profile_id' => '2', 'sort_order' => 460),
		array('id' => 47, 'label' => '沖縄県', 'profile_id' => '2', 'sort_order' => 470),
	),
);

return Site_Config::merge_module_configs($config, 'db_fixture');
