<?php

$config = array(
	'noterm' => array(
		'dropdown' => 'chevron-down',
	),
	'form' => array(
		'submit' => 'edit',
		'do_submit' => 'edit',
		'create' => 'plus',
		'create_simple' => 'plus',
		'do_create' => 'plus',
		'edit' => 'edit',
		'do_edit' => 'pencil',
		'edit_all' => 'edit',
		'delete' => 'trash',
		'do_delete' => 'trash',
		'delete_all' => 'trash',
		'upload' => 'upload',
		'update' => 'refresh',
		'updated' => 'refresh',
		//'confirm' => '確認',
		//'do_confirm' => '確認',
		'back' => 'arrow-left',
		'error' => 'warning-sign',
		'draft' => 'save',
		'preview' => 'eye-open',
		'publish' => 'globe',
		'do_publish' => 'globe',
		'published' => 'globe',
		'unpublish' => 'lock',
		'do_unpublish' => 'lock',
		//'choice' => '選択',
		//'choices' => '選択肢',
		//'operation' => '操作',
		//'operation_all' => '一括操作',
		//'use' => '使用する',
		//'unuse' => '使用しない',
		'search' => 'search',
		//'default' => '初期',
		//'value' => '値',
		//'format' => '形式',
		//'required' => '必須',
		//'place' => '場所',
		'enabled' => 'ok-circle',
		'disabled' => 'ban-circle',
		'add' => 'plus',
		'do_add' => 'plus',
		'add_picture' => 'camera',
		'add_image' => 'camera',
		'insert_picture' => 'plus',
		'add_file' => 'file',
		'add_link' => 'link',
		//'comment' => 'コメント',
		//'do_comment' => 'コメントする',
		'like' => 'thumbs-up',
		'do_like' => 'thumbs-up',
		'undo_like' => 'thumbs-up',
		//'recieve' => '受け取る',
		//'unrecieve' => '受け取らない',
		'watch' => 'eye-open',
		'do_watch' => 'eye-open',
		'do_unwatch' => 'eye-close',
		//'post' => '投稿',
		//'do_post' => '投稿する',
		'save' => 'save',
		'do_save' => 'save',
		'do_reset_default' => array(
			'key' => 'undo',
			'prefix' => 'fa fa-',
		),
		'set_location' => 'map-marker',
		'do_set_location' => 'map-marker',
		'invite' => 'envelope',
		'do_invite' => 'envelope',
		'invite_friend' => 'envelope',
	),
	'site' => array(
		//'view' => 'サイト',
		//'signup'  => 'サインアップ',
		'login' => 'log-in',
		'logout' => 'log-out',
		'register' => 'plus',
		'registration' => 'plus',
		'leave' => 'exclamation-sign',
		//'left' => '退会',
		'setting' => 'cog',
		//'set_already' => '設定済',
		//'unset' => '未設定',
		'mail' => 'envelope',
		'email' => 'envelope',
		'password' => 'lock',
		//'item' => '項目',
		'list' => 'list',
		'management' => 'cog',
		//'last' => '最終',
		'date' => 'calendar',
		'datetime' => 'time',
		//'option' => 'オプション',
		//'id' => 'ID',
		'user' => 'user',
		'picture' => 'picture',
		'file' => 'file',
		//'title' => 'タイトル',
		//'latest' => '最新の',
		//'display' => '表示',
		'detail' => array(
			'key' => 'file-o',
			'prefix' => 'fa fa-',
		),
		'show_detail' => array(
			'key' => 'file-o',
			'prefix' => 'fa fa-',
		),
		'link' => 'link',
		'shot' => 'camera',
		'see_more' => 'caret-down',
		'see_latest' => 'caret-up',
		'forward' => 'forward',
		'backward' => 'backward',
		'tag' => 'tags',
	),
	'member' => array(
		'view' => 'user',
		//'left' => '退会メンバー',
		//'name' => 'ニックネーム',
		//'email' => 'メールアドレス',
		//'password' => 'パスワード',
		//'sex' => array(
		//	'label' => '性別',
		//	'options' => array(
		//		'male' => '男性',
		//		'femail' => '女性',
		//	),
		//),
		//'birthyear' => '生年',
		//'birthday' => '誕生日',
		//'birthyear_birthday' => '生年月日',
		//'age' => '年齢',
		//'generation' => '年代',
		'registration' => 'plus',
	),
	'page' => array(
		//'view' => '画面',
		//'top' => 'Top',
		'myhome'  => 'home',
	),
	//'symbol' => array(
	//	'bool' => array(
	//		'true' => '◯',
	//		'false' => '×',
	//	),
	//	'noValue' => '-',
	//),
	'profile' => 'user',
	//'guest'   => 'Guest',
	//'follow'  => 'フォロー',
	'do_follow' => array(
		'key' => 'square-o',
		'prefix' => 'fa fa-',
	),
	'followed' => array(
		'key' => 'check-square-o',
		'prefix' => 'fa fa-',
	),
	//'friend' => 'フレンド',
	//'remember_me'  => '次回から自動的にログイン',
	'public_flag' => array(
		'label' => '公開範囲',
		'options' => array(
			FBD_PUBLIC_FLAG_PRIVATE => 'lock',
			FBD_PUBLIC_FLAG_ALL => 'globe',
			FBD_PUBLIC_FLAG_MEMBER => 'group',
			//'friend'  => 'user',
		),
	),
);

return Site_Config::merge_module_configs($config, 'icon');
