<?php

$config = array(
	'form' => array(
		'submit' => 'edit',
		'create' => 'plus',
		'do_create' => 'plus',
		'edit' => 'edit',
		'do_edit' => 'pencil',
		'edit_all' => 'edit',
		'delete' => 'trash',
		'do_delete' => 'trash',
		'delete_all' => 'trash',
		'upload' => 'upload',
		'update' => 'refresh',
		'updated' => 'refresh',
		//'confirm' => '確認',
		'back' => 'arrow-left',
		'error' => 'warning-sign',
		'draft' => 'save',
		'preview' => 'eye-open',
		'publish' => 'globe',
		'do_publish' => 'globe',
		'published' => 'globe',
		'unpublish' => 'lock',
		'do_unpublish' => 'lock',
		//'choice' => '選択',
		//'choices' => '選択肢',
		//'operation' => '操作',
		//'use' => '使用する',
		//'unuse' => '使用しない',
		'search' => 'search',
		//'default' => '初期',
		//'value' => '値',
		//'format' => '形式',
		//'required' => '必須',
		//'place' => '場所',
		'enabled' => 'ok-circle',
		'disabled' => 'ban-circle',
		'add' => 'plus',
		'do_add' => 'plus',
		'add_picture' => 'camera',
	),
	'site' => array(
		//'view' => 'サイト',
		//'signup'  => 'サインアップ',
		'login' => 'log-in',
		'logout' => 'log-out',
		'register' => 'plus',
		'registration' => 'plus',
		'leave' => 'exclamation-sign',
		//'left' => '退会',
		'setting' => 'cog',
		//'set_already' => '設定済',
		//'unset' => '未設定',
		'mail' => 'envelope',
		'email' => 'envelope',
		'password' => 'lock',
		//'item' => '項目',
		'list' => 'list',
		'management' => 'cog',
		//'last' => '最終',
		'date' => 'calendar',
		'datetime' => 'time',
		//'option' => 'オプション',
		//'id' => 'ID',
		'user' => 'user',
	),
	'member' => array(
		'view' => 'user',
		//'left' => '退会メンバー',
		//'name' => 'ニックネーム',
		//'email' => 'メールアドレス',
		//'password' => 'パスワード',
		//'sex' => array(
		//	'label' => '性別',
		//	'options' => array(
		//		'male' => '男性',
		//		'femail' => '女性',
		//	),
		//),
		//'birthyear' => '生年',
		//'birthday' => '誕生日',
		//'birthyear_birthday' => '生年月日',
		//'age' => '年齢',
		//'generation' => '年代',
	),
	'page' => array(
		//'view' => '画面',
		//'top' => 'Top',
		'myhome'  => 'home',
	),
	//'symbol' => array(
	//	'bool' => array(
	//		'true' => '◯',
	//		'false' => '×',
	//	),
	//	'noValue' => '-',
	//),
	'profile' => 'user',
	//'guest'   => 'Guest',
	//'follow'  => 'フォロー',
	//'do_follow' => 'フォローする',
	//'followed'  => 'フォロー中',
	//'friend' => 'フレンド',
	//'remember_me'  => '次回から自動的にログイン',
	'public_flag' => array(
		'label' => '公開範囲',
		'options' => array(
			PRJ_PUBLIC_FLAG_PRIVATE => 'lock',
			PRJ_PUBLIC_FLAG_ALL => 'globe',
			PRJ_PUBLIC_FLAG_MEMBER => 'group',
			//'friend'  => 'user',
		),
	),
);

return Site_Util::merge_module_configs($config, 'icon');
