<?php

$config = array(
	'form' => array(
		'submit' => '送信',
		'create' => '新規作成',
		'do_create' => '作成する',
		'edit' => '編集',
		'do_edit' => '編集する',
		'delete' => '削除',
		'do_delete' => '削除する',
		'upload' => 'アップロード',
		'update' => '変更',
		'confirm' => '確認',
		'back' => '戻る',
		'error' => 'エラー',
		'draft' => '下書き保存',
		'preview' => 'プレビュー',
		'publish' => '公開',
		'do_publish' => '公開する',
		'published' => '公開済み',
		'unpublish' => '非公開',
		'do_unpublish' => '非公開にする',
		'updated' => '更新',
		'choice' => '選択',
		'choices' => '選択肢',
		'operation' => '操作',
		'use' => '使用する',
		'unuse' => '使用しない',
		'search' => '検索',
		'default' => '初期',
		'value' => '値',
		'format' => '形式',
		'required' => '必須',
		'place' => '場所',
		'enabled' => '有効',
		'disabled' => '無効',
		'add' => '追加',
		'do_add' => '追加する',
	),
	'site' => array(
		'view' => 'サイト',
		'signup'  => 'Sign Up',
		'login' => 'ログイン',
		'logout' => 'ログアウト',
		'register' => '登録する',
		'registration' => '登録',
		'leave' => '退会する',
		'left' => '退会',
		'setting' => '設定',
		'set_already' => '設定済',
		'unset' => '未設定',
		'mail' => 'メール',
		'email' => 'メールアドレス',
		'password' => 'パスワード',
		'item' => '項目',
		'list' => '一覧',
		'management' => '管理',
		'last' => '最終',
		'date' => '日',
		'datetime' => '日時',
		'option' => 'オプション',
		'id' => 'ID',
		'user' => 'ユーザ',
	),
	'member' => array(
		'view' => 'メンバー',
		'left' => '退会メンバー',
		'name' => 'ニックネーム',
		'email' => 'メールアドレス',
		'password' => 'パスワード',
		'sex' => array(
			'label' => '性別',
			'options' => array(
				'male' => '男性',
				'femail' => '女性',
			),
		),
		'birthyear' => '生年',
		'birthday' => '誕生日',
		'birthyear_birthday' => '生年月日',
		'age' => '年齢',
		'generation' => '年代',
	),
	'page' => array(
		'view' => '画面',
		'top' => 'Top',
		'myhome'  => 'Home',
	),
	'symbol' => array(
		'bool' => array(
			'true' => '◯',
			'false' => '×',
		),
		'noValue' => '-',
	),
	'profile' => 'プロフィール',
	'guest'   => 'Guest',
	'follow'  => 'フォロー',
	'do_follow' => 'フォローする',
	'followed'  => 'フォロー中',
	'friend' => 'フレンド',
	'remember_me'  => '次回から自動的にログイン',
	'public_flag' => array(
		'label' => '公開範囲',
		'options' => array(
			PRJ_PUBLIC_FLAG_PRIVATE => '非公開',
			PRJ_PUBLIC_FLAG_ALL => '全公開',
			PRJ_PUBLIC_FLAG_MEMBER => 'SNS内でのみ公開',
			//'friend'  => 'フレンドまで公開',
		),
	),
);

return Site_Util::merge_module_configs($config, 'term');
