<?php

$config = array(
	'form' => array(
		'submit' => '送信',
		'create' => '新規作成',
		'edit' => '編集',
		'do_edit' => '編集する',
		'delete' => '削除',
		'upload' => 'アップロード',
		'update' => '変更',
		'confirm' => '確認',
		'back' => '戻る',
	),
	'site' => array(
		'site' => 'サイト',
		'view' => '表示',
		'login' => 'ログイン',
		'register' => '登録する',
		'registlation' => '登録',
		'leave' => '退会する',
		'left' => '退会',
		'setting' => '設定',
		'set_already' => '設定済',
		'unset' => '未設定',
		'mail' => 'メール',
		'email' => 'メールアドレス',
		'password' => 'パスワード',
		'item' => '項目',
		'list' => '一覧',
	),
	'member' => array(
		'view' => 'メンバー',
		'left' => '退会メンバー',
		'name' => 'ニックネーム',
		'email' => 'メールアドレス',
		'password' => 'パスワード',
		'sex' => array(
			'label' => '性別',
			'options' => array(
				'male' => '男性',
				'femail' => '女性',
			),
		),
		'birthyear' => '生年',
		'birthday' => '誕生日',
		'birthyear_birthday' => '生年月日',
		'age' => '年齢',
	),
	'toppage' => 'Top',
	'myhome'  => 'Home',
	'profile' => 'Profile',
	'signup'  => 'Sign Up',
	'guest'   => 'Guest',
	'follow'  => 'フォロー',
	'do_follow' => 'フォローする',
	'followed'  => 'フォロー中',
	'friend' => 'フレンド',
	'remember_me'  => '次回から自動的にログイン',
	'public_flag' => array(
		'label' => '公開範囲',
		'options' => array(
			PRJ_PUBLIC_FLAG_PRIVATE => '非公開',
			PRJ_PUBLIC_FLAG_ALL => '全公開',
			PRJ_PUBLIC_FLAG_MEMBER => 'SNS内でのみ公開',
			//'friend'  => 'フレンドまで公開',
		),
	),
);

return Site_Util::merge_module_configs($config, 'term');
